// Code generated by hertz generator. Handler implementations filled manually.

package api

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"

	apimodel "byte.dance/api/biz/model/api"
	"byte.dance/api/biz/rpc"
	"byte.dance/kitex_gen/article"
	"byte.dance/kitex_gen/user"
)

// Register .
// @router /api/v1/user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req apimodel.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(http.StatusBadRequest, &apimodel.RegisterResp{
			Code:    10001,
			Message: err.Error(),
		})
		return
	}

	r, err := rpc.UserClient().Register(context.Background(), &user.RegisterRequest{
		Username: req.Username,
		Email:    req.Email,
		Password: req.Password,
	})
	if err != nil {
		c.JSON(http.StatusInternalServerError, &apimodel.RegisterResp{
			Code:    10002,
			Message: err.Error(),
		})
		return
	}

	c.JSON(http.StatusOK, &apimodel.RegisterResp{
		Code:    0,
		Message: "success",
		UserID:  r.UserId,
		Token:   r.Token,
	})
}

// Login .
// @router /api/v1/user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req apimodel.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(http.StatusBadRequest, &apimodel.LoginResp{
			Code:    10001,
			Message: err.Error(),
		})
		return
	}

	r, err := rpc.UserClient().Login(context.Background(), &user.LoginRequest{
		Username: req.Username,
		Password: req.Password,
	})
	if err != nil {
		c.JSON(http.StatusInternalServerError, &apimodel.LoginResp{
			Code:    10002,
			Message: err.Error(),
		})
		return
	}

	c.JSON(http.StatusOK, &apimodel.LoginResp{
		Code:    0,
		Message: "success",
		UserID:  r.UserId,
		Token:   r.Token,
	})
}

// GetUser .
// @router /api/v1/user/:id [GET]
func GetUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req apimodel.GetUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(http.StatusBadRequest, utils.H{"code": 10001, "message": err.Error()})
		return
	}

	r, err := rpc.UserClient().GetUser(context.Background(), &user.GetUserRequest{
		UserId: req.ID,
	})
	if err != nil {
		c.JSON(http.StatusInternalServerError, utils.H{"code": 10002, "message": err.Error()})
		return
	}

	c.JSON(http.StatusOK, &apimodel.GetUserResp{
		Code:      0,
		Message:   "success",
		ID:        r.User.Id,
		Username:  r.User.Username,
		Email:     r.User.Email,
		Avatar:    r.User.Avatar,
		CreatedAt: r.User.CreatedAt,
		UpdatedAt: r.User.UpdatedAt,
	})
}

// UpdateUser .
// @router /api/v1/user/:id [PUT]
func UpdateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req apimodel.UpdateUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(http.StatusBadRequest, &apimodel.UpdateUserResp{
			Code:    10001,
			Message: err.Error(),
		})
		return
	}

	_, err = rpc.UserClient().UpdateUser(context.Background(), &user.UpdateUserRequest{
		UserId:   req.ID,
		Username: req.Username,
		Email:    req.Email,
		Avatar:   req.Avatar,
	})
	if err != nil {
		c.JSON(http.StatusInternalServerError, &apimodel.UpdateUserResp{
			Code:    10002,
			Message: err.Error(),
		})
		return
	}

	c.JSON(http.StatusOK, &apimodel.UpdateUserResp{
		Code:    0,
		Message: "success",
	})
}

// CreateArticle .
// @router /api/v1/article [POST]
func CreateArticle(ctx context.Context, c *app.RequestContext) {
	var err error
	var req apimodel.CreateArticleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(http.StatusBadRequest, &apimodel.CreateArticleResp{
			Code:    10001,
			Message: err.Error(),
		})
		return
	}

	uid, _ := c.Get("user_id")
	userID, _ := uid.(int64)

	r, err := rpc.ArticleClient().CreateArticle(context.Background(), &article.CreateArticleRequest{
		Title:    req.Title,
		Content:  req.Content,
		AuthorId: userID,
	})
	if err != nil {
		c.JSON(http.StatusInternalServerError, &apimodel.CreateArticleResp{
			Code:    10002,
			Message: err.Error(),
		})
		return
	}

	c.JSON(http.StatusOK, &apimodel.CreateArticleResp{
		Code:      0,
		Message:   "success",
		ArticleID: r.ArticleId,
	})
}

// GetArticle .
// @router /api/v1/article/:id [GET]
func GetArticle(ctx context.Context, c *app.RequestContext) {
	var err error
	var req apimodel.GetArticleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(http.StatusBadRequest, utils.H{"code": 10001, "message": err.Error()})
		return
	}

	r, err := rpc.ArticleClient().GetArticle(context.Background(), &article.GetArticleRequest{
		ArticleId: req.ID,
	})
	if err != nil {
		c.JSON(http.StatusInternalServerError, utils.H{"code": 10002, "message": err.Error()})
		return
	}

	c.JSON(http.StatusOK, &apimodel.GetArticleResp{
		Code:       0,
		Message:    "success",
		ID:         r.Article.Id,
		Title:      r.Article.Title,
		Content:    r.Article.Content,
		AuthorID:   r.Article.AuthorId,
		AuthorName: r.Article.AuthorName,
		Status:     r.Article.Status,
		ViewCount:  r.Article.ViewCount,
		CreatedAt:  r.Article.CreatedAt,
		UpdatedAt:  r.Article.UpdatedAt,
	})
}

// ListArticle .
// @router /api/v1/articles [GET]
func ListArticle(ctx context.Context, c *app.RequestContext) {
	var err error
	var req apimodel.ListArticleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(http.StatusBadRequest, utils.H{"code": 10001, "message": err.Error()})
		return
	}

	r, err := rpc.ArticleClient().ListArticle(context.Background(), &article.ListArticleRequest{
		AuthorId: req.AuthorID,
		Page:     req.Page,
		PageSize: req.PageSize,
	})
	if err != nil {
		c.JSON(http.StatusInternalServerError, utils.H{"code": 10002, "message": err.Error()})
		return
	}

	dataBytes, _ := json.Marshal(utils.H{
		"articles": r.Articles,
		"total":    r.Total,
	})
	c.JSON(http.StatusOK, &apimodel.ListArticleResp{
		Code:    0,
		Message: "success",
		Data:    string(dataBytes),
	})
}

// UpdateArticle .
// @router /api/v1/article/:id [PUT]
func UpdateArticle(ctx context.Context, c *app.RequestContext) {
	var err error
	var req apimodel.UpdateArticleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(http.StatusBadRequest, &apimodel.UpdateArticleResp{
			Code:    10001,
			Message: err.Error(),
		})
		return
	}

	_, err = rpc.ArticleClient().UpdateArticle(context.Background(), &article.UpdateArticleRequest{
		ArticleId: req.ID,
		Title:     req.Title,
		Content:   req.Content,
		Status:    req.Status,
	})
	if err != nil {
		c.JSON(http.StatusInternalServerError, &apimodel.UpdateArticleResp{
			Code:    10002,
			Message: err.Error(),
		})
		return
	}

	c.JSON(http.StatusOK, &apimodel.UpdateArticleResp{
		Code:    0,
		Message: "success",
	})
}

// DeleteArticle .
// @router /api/v1/article/:id [DELETE]
func DeleteArticle(ctx context.Context, c *app.RequestContext) {
	var err error
	var req apimodel.DeleteArticleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(http.StatusBadRequest, &apimodel.DeleteArticleResp{
			Code:    10001,
			Message: err.Error(),
		})
		return
	}

	_, err = rpc.ArticleClient().DeleteArticle(context.Background(), &article.DeleteArticleRequest{
		ArticleId: req.ID,
	})
	if err != nil {
		c.JSON(http.StatusInternalServerError, &apimodel.DeleteArticleResp{
			Code:    10002,
			Message: err.Error(),
		})
		return
	}

	c.JSON(http.StatusOK, &apimodel.DeleteArticleResp{
		Code:    0,
		Message: "success",
	})
}
