// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package article

import (
	"context"
	"fmt"
)

type Article struct {
	Id         int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Title      string `thrift:"title,2" frugal:"2,default,string" json:"title"`
	Content    string `thrift:"content,3" frugal:"3,default,string" json:"content"`
	AuthorId   int64  `thrift:"author_id,4" frugal:"4,default,i64" json:"author_id"`
	AuthorName string `thrift:"author_name,5" frugal:"5,default,string" json:"author_name"`
	Status     int32  `thrift:"status,6" frugal:"6,default,i32" json:"status"`
	ViewCount  int64  `thrift:"view_count,7" frugal:"7,default,i64" json:"view_count"`
	CreatedAt  string `thrift:"created_at,8" frugal:"8,default,string" json:"created_at"`
	UpdatedAt  string `thrift:"updated_at,9" frugal:"9,default,string" json:"updated_at"`
}

func NewArticle() *Article {
	return &Article{}
}

func (p *Article) InitDefault() {
}

func (p *Article) GetId() (v int64) {
	return p.Id
}

func (p *Article) GetTitle() (v string) {
	return p.Title
}

func (p *Article) GetContent() (v string) {
	return p.Content
}

func (p *Article) GetAuthorId() (v int64) {
	return p.AuthorId
}

func (p *Article) GetAuthorName() (v string) {
	return p.AuthorName
}

func (p *Article) GetStatus() (v int32) {
	return p.Status
}

func (p *Article) GetViewCount() (v int64) {
	return p.ViewCount
}

func (p *Article) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *Article) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}
func (p *Article) SetId(val int64) {
	p.Id = val
}
func (p *Article) SetTitle(val string) {
	p.Title = val
}
func (p *Article) SetContent(val string) {
	p.Content = val
}
func (p *Article) SetAuthorId(val int64) {
	p.AuthorId = val
}
func (p *Article) SetAuthorName(val string) {
	p.AuthorName = val
}
func (p *Article) SetStatus(val int32) {
	p.Status = val
}
func (p *Article) SetViewCount(val int64) {
	p.ViewCount = val
}
func (p *Article) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *Article) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}

func (p *Article) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Article(%+v)", *p)
}

var fieldIDToName_Article = map[int16]string{
	1: "id",
	2: "title",
	3: "content",
	4: "author_id",
	5: "author_name",
	6: "status",
	7: "view_count",
	8: "created_at",
	9: "updated_at",
}

type CreateArticleRequest struct {
	Title    string `thrift:"title,1" frugal:"1,default,string" json:"title"`
	Content  string `thrift:"content,2" frugal:"2,default,string" json:"content"`
	AuthorId int64  `thrift:"author_id,3" frugal:"3,default,i64" json:"author_id"`
}

func NewCreateArticleRequest() *CreateArticleRequest {
	return &CreateArticleRequest{}
}

func (p *CreateArticleRequest) InitDefault() {
}

func (p *CreateArticleRequest) GetTitle() (v string) {
	return p.Title
}

func (p *CreateArticleRequest) GetContent() (v string) {
	return p.Content
}

func (p *CreateArticleRequest) GetAuthorId() (v int64) {
	return p.AuthorId
}
func (p *CreateArticleRequest) SetTitle(val string) {
	p.Title = val
}
func (p *CreateArticleRequest) SetContent(val string) {
	p.Content = val
}
func (p *CreateArticleRequest) SetAuthorId(val int64) {
	p.AuthorId = val
}

func (p *CreateArticleRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateArticleRequest(%+v)", *p)
}

var fieldIDToName_CreateArticleRequest = map[int16]string{
	1: "title",
	2: "content",
	3: "author_id",
}

type CreateArticleResponse struct {
	ArticleId int64 `thrift:"article_id,1" frugal:"1,default,i64" json:"article_id"`
}

func NewCreateArticleResponse() *CreateArticleResponse {
	return &CreateArticleResponse{}
}

func (p *CreateArticleResponse) InitDefault() {
}

func (p *CreateArticleResponse) GetArticleId() (v int64) {
	return p.ArticleId
}
func (p *CreateArticleResponse) SetArticleId(val int64) {
	p.ArticleId = val
}

func (p *CreateArticleResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateArticleResponse(%+v)", *p)
}

var fieldIDToName_CreateArticleResponse = map[int16]string{
	1: "article_id",
}

type GetArticleRequest struct {
	ArticleId int64 `thrift:"article_id,1" frugal:"1,default,i64" json:"article_id"`
}

func NewGetArticleRequest() *GetArticleRequest {
	return &GetArticleRequest{}
}

func (p *GetArticleRequest) InitDefault() {
}

func (p *GetArticleRequest) GetArticleId() (v int64) {
	return p.ArticleId
}
func (p *GetArticleRequest) SetArticleId(val int64) {
	p.ArticleId = val
}

func (p *GetArticleRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetArticleRequest(%+v)", *p)
}

var fieldIDToName_GetArticleRequest = map[int16]string{
	1: "article_id",
}

type GetArticleResponse struct {
	Article *Article `thrift:"article,1" frugal:"1,default,Article" json:"article"`
}

func NewGetArticleResponse() *GetArticleResponse {
	return &GetArticleResponse{}
}

func (p *GetArticleResponse) InitDefault() {
}

var GetArticleResponse_Article_DEFAULT *Article

func (p *GetArticleResponse) GetArticle() (v *Article) {
	if !p.IsSetArticle() {
		return GetArticleResponse_Article_DEFAULT
	}
	return p.Article
}
func (p *GetArticleResponse) SetArticle(val *Article) {
	p.Article = val
}

func (p *GetArticleResponse) IsSetArticle() bool {
	return p.Article != nil
}

func (p *GetArticleResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetArticleResponse(%+v)", *p)
}

var fieldIDToName_GetArticleResponse = map[int16]string{
	1: "article",
}

type ListArticleRequest struct {
	AuthorId int64 `thrift:"author_id,1" frugal:"1,default,i64" json:"author_id"`
	Page     int32 `thrift:"page,2" frugal:"2,default,i32" json:"page"`
	PageSize int32 `thrift:"page_size,3" frugal:"3,default,i32" json:"page_size"`
}

func NewListArticleRequest() *ListArticleRequest {
	return &ListArticleRequest{}
}

func (p *ListArticleRequest) InitDefault() {
}

func (p *ListArticleRequest) GetAuthorId() (v int64) {
	return p.AuthorId
}

func (p *ListArticleRequest) GetPage() (v int32) {
	return p.Page
}

func (p *ListArticleRequest) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *ListArticleRequest) SetAuthorId(val int64) {
	p.AuthorId = val
}
func (p *ListArticleRequest) SetPage(val int32) {
	p.Page = val
}
func (p *ListArticleRequest) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *ListArticleRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListArticleRequest(%+v)", *p)
}

var fieldIDToName_ListArticleRequest = map[int16]string{
	1: "author_id",
	2: "page",
	3: "page_size",
}

type ListArticleResponse struct {
	Articles []*Article `thrift:"articles,1" frugal:"1,default,list<Article>" json:"articles"`
	Total    int64      `thrift:"total,2" frugal:"2,default,i64" json:"total"`
}

func NewListArticleResponse() *ListArticleResponse {
	return &ListArticleResponse{}
}

func (p *ListArticleResponse) InitDefault() {
}

func (p *ListArticleResponse) GetArticles() (v []*Article) {
	return p.Articles
}

func (p *ListArticleResponse) GetTotal() (v int64) {
	return p.Total
}
func (p *ListArticleResponse) SetArticles(val []*Article) {
	p.Articles = val
}
func (p *ListArticleResponse) SetTotal(val int64) {
	p.Total = val
}

func (p *ListArticleResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListArticleResponse(%+v)", *p)
}

var fieldIDToName_ListArticleResponse = map[int16]string{
	1: "articles",
	2: "total",
}

type UpdateArticleRequest struct {
	ArticleId int64  `thrift:"article_id,1" frugal:"1,default,i64" json:"article_id"`
	Title     string `thrift:"title,2" frugal:"2,default,string" json:"title"`
	Content   string `thrift:"content,3" frugal:"3,default,string" json:"content"`
	Status    int32  `thrift:"status,4" frugal:"4,default,i32" json:"status"`
}

func NewUpdateArticleRequest() *UpdateArticleRequest {
	return &UpdateArticleRequest{}
}

func (p *UpdateArticleRequest) InitDefault() {
}

func (p *UpdateArticleRequest) GetArticleId() (v int64) {
	return p.ArticleId
}

func (p *UpdateArticleRequest) GetTitle() (v string) {
	return p.Title
}

func (p *UpdateArticleRequest) GetContent() (v string) {
	return p.Content
}

func (p *UpdateArticleRequest) GetStatus() (v int32) {
	return p.Status
}
func (p *UpdateArticleRequest) SetArticleId(val int64) {
	p.ArticleId = val
}
func (p *UpdateArticleRequest) SetTitle(val string) {
	p.Title = val
}
func (p *UpdateArticleRequest) SetContent(val string) {
	p.Content = val
}
func (p *UpdateArticleRequest) SetStatus(val int32) {
	p.Status = val
}

func (p *UpdateArticleRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateArticleRequest(%+v)", *p)
}

var fieldIDToName_UpdateArticleRequest = map[int16]string{
	1: "article_id",
	2: "title",
	3: "content",
	4: "status",
}

type UpdateArticleResponse struct {
	Success bool `thrift:"success,1" frugal:"1,default,bool" json:"success"`
}

func NewUpdateArticleResponse() *UpdateArticleResponse {
	return &UpdateArticleResponse{}
}

func (p *UpdateArticleResponse) InitDefault() {
}

func (p *UpdateArticleResponse) GetSuccess() (v bool) {
	return p.Success
}
func (p *UpdateArticleResponse) SetSuccess(val bool) {
	p.Success = val
}

func (p *UpdateArticleResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateArticleResponse(%+v)", *p)
}

var fieldIDToName_UpdateArticleResponse = map[int16]string{
	1: "success",
}

type DeleteArticleRequest struct {
	ArticleId int64 `thrift:"article_id,1" frugal:"1,default,i64" json:"article_id"`
}

func NewDeleteArticleRequest() *DeleteArticleRequest {
	return &DeleteArticleRequest{}
}

func (p *DeleteArticleRequest) InitDefault() {
}

func (p *DeleteArticleRequest) GetArticleId() (v int64) {
	return p.ArticleId
}
func (p *DeleteArticleRequest) SetArticleId(val int64) {
	p.ArticleId = val
}

func (p *DeleteArticleRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteArticleRequest(%+v)", *p)
}

var fieldIDToName_DeleteArticleRequest = map[int16]string{
	1: "article_id",
}

type DeleteArticleResponse struct {
	Success bool `thrift:"success,1" frugal:"1,default,bool" json:"success"`
}

func NewDeleteArticleResponse() *DeleteArticleResponse {
	return &DeleteArticleResponse{}
}

func (p *DeleteArticleResponse) InitDefault() {
}

func (p *DeleteArticleResponse) GetSuccess() (v bool) {
	return p.Success
}
func (p *DeleteArticleResponse) SetSuccess(val bool) {
	p.Success = val
}

func (p *DeleteArticleResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteArticleResponse(%+v)", *p)
}

var fieldIDToName_DeleteArticleResponse = map[int16]string{
	1: "success",
}

type ArticleService interface {
	CreateArticle(ctx context.Context, req *CreateArticleRequest) (r *CreateArticleResponse, err error)

	GetArticle(ctx context.Context, req *GetArticleRequest) (r *GetArticleResponse, err error)

	ListArticle(ctx context.Context, req *ListArticleRequest) (r *ListArticleResponse, err error)

	UpdateArticle(ctx context.Context, req *UpdateArticleRequest) (r *UpdateArticleResponse, err error)

	DeleteArticle(ctx context.Context, req *DeleteArticleRequest) (r *DeleteArticleResponse, err error)
}

type ArticleServiceCreateArticleArgs struct {
	Req *CreateArticleRequest `thrift:"req,1" frugal:"1,default,CreateArticleRequest" json:"req"`
}

func NewArticleServiceCreateArticleArgs() *ArticleServiceCreateArticleArgs {
	return &ArticleServiceCreateArticleArgs{}
}

func (p *ArticleServiceCreateArticleArgs) InitDefault() {
}

var ArticleServiceCreateArticleArgs_Req_DEFAULT *CreateArticleRequest

func (p *ArticleServiceCreateArticleArgs) GetReq() (v *CreateArticleRequest) {
	if !p.IsSetReq() {
		return ArticleServiceCreateArticleArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ArticleServiceCreateArticleArgs) SetReq(val *CreateArticleRequest) {
	p.Req = val
}

func (p *ArticleServiceCreateArticleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ArticleServiceCreateArticleArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ArticleServiceCreateArticleArgs(%+v)", *p)
}

var fieldIDToName_ArticleServiceCreateArticleArgs = map[int16]string{
	1: "req",
}

type ArticleServiceCreateArticleResult struct {
	Success *CreateArticleResponse `thrift:"success,0,optional" frugal:"0,optional,CreateArticleResponse" json:"success,omitempty"`
}

func NewArticleServiceCreateArticleResult() *ArticleServiceCreateArticleResult {
	return &ArticleServiceCreateArticleResult{}
}

func (p *ArticleServiceCreateArticleResult) InitDefault() {
}

var ArticleServiceCreateArticleResult_Success_DEFAULT *CreateArticleResponse

func (p *ArticleServiceCreateArticleResult) GetSuccess() (v *CreateArticleResponse) {
	if !p.IsSetSuccess() {
		return ArticleServiceCreateArticleResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ArticleServiceCreateArticleResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateArticleResponse)
}

func (p *ArticleServiceCreateArticleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ArticleServiceCreateArticleResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ArticleServiceCreateArticleResult(%+v)", *p)
}

var fieldIDToName_ArticleServiceCreateArticleResult = map[int16]string{
	0: "success",
}

type ArticleServiceGetArticleArgs struct {
	Req *GetArticleRequest `thrift:"req,1" frugal:"1,default,GetArticleRequest" json:"req"`
}

func NewArticleServiceGetArticleArgs() *ArticleServiceGetArticleArgs {
	return &ArticleServiceGetArticleArgs{}
}

func (p *ArticleServiceGetArticleArgs) InitDefault() {
}

var ArticleServiceGetArticleArgs_Req_DEFAULT *GetArticleRequest

func (p *ArticleServiceGetArticleArgs) GetReq() (v *GetArticleRequest) {
	if !p.IsSetReq() {
		return ArticleServiceGetArticleArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ArticleServiceGetArticleArgs) SetReq(val *GetArticleRequest) {
	p.Req = val
}

func (p *ArticleServiceGetArticleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ArticleServiceGetArticleArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ArticleServiceGetArticleArgs(%+v)", *p)
}

var fieldIDToName_ArticleServiceGetArticleArgs = map[int16]string{
	1: "req",
}

type ArticleServiceGetArticleResult struct {
	Success *GetArticleResponse `thrift:"success,0,optional" frugal:"0,optional,GetArticleResponse" json:"success,omitempty"`
}

func NewArticleServiceGetArticleResult() *ArticleServiceGetArticleResult {
	return &ArticleServiceGetArticleResult{}
}

func (p *ArticleServiceGetArticleResult) InitDefault() {
}

var ArticleServiceGetArticleResult_Success_DEFAULT *GetArticleResponse

func (p *ArticleServiceGetArticleResult) GetSuccess() (v *GetArticleResponse) {
	if !p.IsSetSuccess() {
		return ArticleServiceGetArticleResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ArticleServiceGetArticleResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetArticleResponse)
}

func (p *ArticleServiceGetArticleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ArticleServiceGetArticleResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ArticleServiceGetArticleResult(%+v)", *p)
}

var fieldIDToName_ArticleServiceGetArticleResult = map[int16]string{
	0: "success",
}

type ArticleServiceListArticleArgs struct {
	Req *ListArticleRequest `thrift:"req,1" frugal:"1,default,ListArticleRequest" json:"req"`
}

func NewArticleServiceListArticleArgs() *ArticleServiceListArticleArgs {
	return &ArticleServiceListArticleArgs{}
}

func (p *ArticleServiceListArticleArgs) InitDefault() {
}

var ArticleServiceListArticleArgs_Req_DEFAULT *ListArticleRequest

func (p *ArticleServiceListArticleArgs) GetReq() (v *ListArticleRequest) {
	if !p.IsSetReq() {
		return ArticleServiceListArticleArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ArticleServiceListArticleArgs) SetReq(val *ListArticleRequest) {
	p.Req = val
}

func (p *ArticleServiceListArticleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ArticleServiceListArticleArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ArticleServiceListArticleArgs(%+v)", *p)
}

var fieldIDToName_ArticleServiceListArticleArgs = map[int16]string{
	1: "req",
}

type ArticleServiceListArticleResult struct {
	Success *ListArticleResponse `thrift:"success,0,optional" frugal:"0,optional,ListArticleResponse" json:"success,omitempty"`
}

func NewArticleServiceListArticleResult() *ArticleServiceListArticleResult {
	return &ArticleServiceListArticleResult{}
}

func (p *ArticleServiceListArticleResult) InitDefault() {
}

var ArticleServiceListArticleResult_Success_DEFAULT *ListArticleResponse

func (p *ArticleServiceListArticleResult) GetSuccess() (v *ListArticleResponse) {
	if !p.IsSetSuccess() {
		return ArticleServiceListArticleResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ArticleServiceListArticleResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListArticleResponse)
}

func (p *ArticleServiceListArticleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ArticleServiceListArticleResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ArticleServiceListArticleResult(%+v)", *p)
}

var fieldIDToName_ArticleServiceListArticleResult = map[int16]string{
	0: "success",
}

type ArticleServiceUpdateArticleArgs struct {
	Req *UpdateArticleRequest `thrift:"req,1" frugal:"1,default,UpdateArticleRequest" json:"req"`
}

func NewArticleServiceUpdateArticleArgs() *ArticleServiceUpdateArticleArgs {
	return &ArticleServiceUpdateArticleArgs{}
}

func (p *ArticleServiceUpdateArticleArgs) InitDefault() {
}

var ArticleServiceUpdateArticleArgs_Req_DEFAULT *UpdateArticleRequest

func (p *ArticleServiceUpdateArticleArgs) GetReq() (v *UpdateArticleRequest) {
	if !p.IsSetReq() {
		return ArticleServiceUpdateArticleArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ArticleServiceUpdateArticleArgs) SetReq(val *UpdateArticleRequest) {
	p.Req = val
}

func (p *ArticleServiceUpdateArticleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ArticleServiceUpdateArticleArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ArticleServiceUpdateArticleArgs(%+v)", *p)
}

var fieldIDToName_ArticleServiceUpdateArticleArgs = map[int16]string{
	1: "req",
}

type ArticleServiceUpdateArticleResult struct {
	Success *UpdateArticleResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateArticleResponse" json:"success,omitempty"`
}

func NewArticleServiceUpdateArticleResult() *ArticleServiceUpdateArticleResult {
	return &ArticleServiceUpdateArticleResult{}
}

func (p *ArticleServiceUpdateArticleResult) InitDefault() {
}

var ArticleServiceUpdateArticleResult_Success_DEFAULT *UpdateArticleResponse

func (p *ArticleServiceUpdateArticleResult) GetSuccess() (v *UpdateArticleResponse) {
	if !p.IsSetSuccess() {
		return ArticleServiceUpdateArticleResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ArticleServiceUpdateArticleResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateArticleResponse)
}

func (p *ArticleServiceUpdateArticleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ArticleServiceUpdateArticleResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ArticleServiceUpdateArticleResult(%+v)", *p)
}

var fieldIDToName_ArticleServiceUpdateArticleResult = map[int16]string{
	0: "success",
}

type ArticleServiceDeleteArticleArgs struct {
	Req *DeleteArticleRequest `thrift:"req,1" frugal:"1,default,DeleteArticleRequest" json:"req"`
}

func NewArticleServiceDeleteArticleArgs() *ArticleServiceDeleteArticleArgs {
	return &ArticleServiceDeleteArticleArgs{}
}

func (p *ArticleServiceDeleteArticleArgs) InitDefault() {
}

var ArticleServiceDeleteArticleArgs_Req_DEFAULT *DeleteArticleRequest

func (p *ArticleServiceDeleteArticleArgs) GetReq() (v *DeleteArticleRequest) {
	if !p.IsSetReq() {
		return ArticleServiceDeleteArticleArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ArticleServiceDeleteArticleArgs) SetReq(val *DeleteArticleRequest) {
	p.Req = val
}

func (p *ArticleServiceDeleteArticleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ArticleServiceDeleteArticleArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ArticleServiceDeleteArticleArgs(%+v)", *p)
}

var fieldIDToName_ArticleServiceDeleteArticleArgs = map[int16]string{
	1: "req",
}

type ArticleServiceDeleteArticleResult struct {
	Success *DeleteArticleResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteArticleResponse" json:"success,omitempty"`
}

func NewArticleServiceDeleteArticleResult() *ArticleServiceDeleteArticleResult {
	return &ArticleServiceDeleteArticleResult{}
}

func (p *ArticleServiceDeleteArticleResult) InitDefault() {
}

var ArticleServiceDeleteArticleResult_Success_DEFAULT *DeleteArticleResponse

func (p *ArticleServiceDeleteArticleResult) GetSuccess() (v *DeleteArticleResponse) {
	if !p.IsSetSuccess() {
		return ArticleServiceDeleteArticleResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ArticleServiceDeleteArticleResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteArticleResponse)
}

func (p *ArticleServiceDeleteArticleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ArticleServiceDeleteArticleResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ArticleServiceDeleteArticleResult(%+v)", *p)
}

var fieldIDToName_ArticleServiceDeleteArticleResult = map[int16]string{
	0: "success",
}
