// Code generated by hertz generator (struct definitions extracted).
// Source IDL: idl/api.thrift
//
// Annotations used in IDL:
//   api.body    -> json / form tags  (request body binding)
//   api.path    -> path tag          (URL path parameter binding)
//   api.query   -> query tag         (query string binding)
//   api.vd      -> vd tag            (parameter validation via go-tagexpr)
//   api.post / api.get / api.put / api.delete -> route registration (see biz/router/api/api.go)

package api

// ====================== Common ======================

type BaseResp struct {
	Code    int32  `form:"code" json:"code"`
	Message string `form:"message" json:"message"`
	Data    string `form:"data" json:"data"`
}

// ====================== User ======================

// RegisterReq — POST /api/v1/user/register
// All fields from api.body (JSON body), validated by api.vd
type RegisterReq struct {
	Username string `form:"username" json:"username" vd:"len($)>1 && len($)<33; msg:'username length must be 2-32'"`
	Email    string `form:"email" json:"email" vd:"len($)>4 && len($)<65; msg:'email length must be 5-64'"`
	Password string `form:"password" json:"password" vd:"len($)>5 && len($)<129; msg:'password length must be 6-128'"`
}

type RegisterResp struct {
	Code    int32  `form:"code" json:"code"`
	Message string `form:"message" json:"message"`
	UserID  int64  `form:"user_id" json:"user_id"`
	Token   string `form:"token" json:"token"`
}

// LoginReq — POST /api/v1/user/login
type LoginReq struct {
	Username string `form:"username" json:"username" vd:"len($)>1; msg:'username is required'"`
	Password string `form:"password" json:"password" vd:"len($)>5; msg:'password length must be >5'"`
}

type LoginResp struct {
	Code    int32  `form:"code" json:"code"`
	Message string `form:"message" json:"message"`
	UserID  int64  `form:"user_id" json:"user_id"`
	Token   string `form:"token" json:"token"`
}

// GetUserReq — GET /api/v1/user/:id
// ID comes from api.path="id" (URL path parameter)
type GetUserReq struct {
	ID int64 `json:"id" path:"id" vd:"$>0; msg:'invalid user id'"`
}

type GetUserResp struct {
	Code      int32  `form:"code" json:"code"`
	Message   string `form:"message" json:"message"`
	ID        int64  `form:"id" json:"id"`
	Username  string `form:"username" json:"username"`
	Email     string `form:"email" json:"email"`
	Avatar    string `form:"avatar" json:"avatar"`
	CreatedAt string `form:"created_at" json:"created_at"`
	UpdatedAt string `form:"updated_at" json:"updated_at"`
}

// UpdateUserReq — PUT /api/v1/user/:id
// ID from api.path, others from api.body
type UpdateUserReq struct {
	ID       int64  `json:"id" path:"id" vd:"$>0; msg:'invalid user id'"`
	Username string `form:"username" json:"username"`
	Email    string `form:"email" json:"email"`
	Avatar   string `form:"avatar" json:"avatar"`
}

type UpdateUserResp struct {
	Code    int32  `form:"code" json:"code"`
	Message string `form:"message" json:"message"`
}

// ====================== Article ======================

// CreateArticleReq — POST /api/v1/article
// Fields from api.body, validated by api.vd
type CreateArticleReq struct {
	Title   string `form:"title" json:"title" vd:"len($)>0 && len($)<257; msg:'title length must be 1-256'"`
	Content string `form:"content" json:"content" vd:"len($)>0; msg:'content is required'"`
}

type CreateArticleResp struct {
	Code      int32  `form:"code" json:"code"`
	Message   string `form:"message" json:"message"`
	ArticleID int64  `form:"article_id" json:"article_id"`
}

// GetArticleReq — GET /api/v1/article/:id
type GetArticleReq struct {
	ID int64 `json:"id" path:"id" vd:"$>0; msg:'invalid article id'"`
}

type GetArticleResp struct {
	Code       int32  `form:"code" json:"code"`
	Message    string `form:"message" json:"message"`
	ID         int64  `form:"id" json:"id"`
	Title      string `form:"title" json:"title"`
	Content    string `form:"content" json:"content"`
	AuthorID   int64  `form:"author_id" json:"author_id"`
	AuthorName string `form:"author_name" json:"author_name"`
	Status     int32  `form:"status" json:"status"`
	ViewCount  int64  `form:"view_count" json:"view_count"`
	CreatedAt  string `form:"created_at" json:"created_at"`
	UpdatedAt  string `form:"updated_at" json:"updated_at"`
}

// ListArticleReq — GET /api/v1/articles
// All fields from api.query (query string parameters)
type ListArticleReq struct {
	AuthorID int64 `json:"author_id" query:"author_id"`
	Page     int32 `json:"page" query:"page" vd:"$>0; msg:'page must be > 0'"`
	PageSize int32 `json:"page_size" query:"page_size" vd:"$>0 && $<=100; msg:'page_size must be 1-100'"`
}

type ListArticleResp struct {
	Code    int32  `form:"code" json:"code"`
	Message string `form:"message" json:"message"`
	Data    string `form:"data" json:"data"`
}

// UpdateArticleReq — PUT /api/v1/article/:id
// ID from api.path, others from api.body
type UpdateArticleReq struct {
	ID      int64  `json:"id" path:"id" vd:"$>0; msg:'invalid article id'"`
	Title   string `form:"title" json:"title"`
	Content string `form:"content" json:"content"`
	Status  int32  `form:"status" json:"status"`
}

type UpdateArticleResp struct {
	Code    int32  `form:"code" json:"code"`
	Message string `form:"message" json:"message"`
}

// DeleteArticleReq — DELETE /api/v1/article/:id
type DeleteArticleReq struct {
	ID int64 `json:"id" path:"id" vd:"$>0; msg:'invalid article id'"`
}

type DeleteArticleResp struct {
	Code    int32  `form:"code" json:"code"`
	Message string `form:"message" json:"message"`
}
