// Code generated by hertz generator.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"

	"byte.dance/pkg/middleware"
)

func rootMw() []app.HandlerFunc {
	return nil
}

func _apiMw() []app.HandlerFunc {
	return nil
}

func _v1Mw() []app.HandlerFunc {
	return nil
}

func _articleMw() []app.HandlerFunc {
	return nil
}

// --- auth-required middleware for write operations ---

func authMw() app.HandlerFunc {
	return func(ctx context.Context, c *app.RequestContext) {
		auth := string(c.GetHeader("Authorization"))
		if auth == "" || !strings.HasPrefix(auth, "Bearer ") {
			c.JSON(http.StatusUnauthorized, utils.H{
				"code":    10003,
				"message": "authentication failed",
			})
			c.Abort()
			return
		}
		tokenStr := strings.TrimPrefix(auth, "Bearer ")
		claims, err := middleware.ParseToken(tokenStr)
		if err != nil {
			c.JSON(http.StatusUnauthorized, utils.H{
				"code":    10003,
				"message": "authentication failed",
			})
			c.Abort()
			return
		}
		c.Set("user_id", claims.UserID)
		c.Next(ctx)
	}
}

func _createarticleMw() []app.HandlerFunc {
	return []app.HandlerFunc{authMw()}
}

func _deletearticleMw() []app.HandlerFunc {
	return []app.HandlerFunc{authMw()}
}

func _getarticleMw() []app.HandlerFunc {
	return nil
}

func _updatearticleMw() []app.HandlerFunc {
	return []app.HandlerFunc{authMw()}
}

func _listarticleMw() []app.HandlerFunc {
	return nil
}

func _userMw() []app.HandlerFunc {
	return nil
}

func _getuserMw() []app.HandlerFunc {
	return nil
}

func _updateuserMw() []app.HandlerFunc {
	return []app.HandlerFunc{authMw()}
}

func _loginMw() []app.HandlerFunc {
	return nil
}

func _registerMw() []app.HandlerFunc {
	return nil
}
